test:centos7:
  variables:
    DOCKER_IMAGE: geerlingguy/docker-centos7-ansible:latest
    PLAYBOOK_EXTRA_VARS: ""
    ANSIBLE_ROLES_PATH: /builds/planet-winter/
  image: $DOCKER_IMAGE
  script:
    - ansible-playbook --syntax-check --extra-vars "$PLAYBOOK_EXTRA_VARS" tests/test.yml
    # Test role
    -  ansible-playbook --extra-vars "$PLAYBOOK_EXTRA_VARS" tests/test.yml
    # Test role idempotence
    - idempotence=$(mktemp)
    - ansible-playbook --extra-vars "$PLAYBOOK_EXTRA_VARS" tests/test.yml | tee -a ${idempotence}
    - >
      tail ${idempotence}
      | grep -q 'changed=0.*failed=0'
      && (echo 'Idempotence test: pass' && exit 0)
      || (echo 'Idempotence test: fail' && exit 1)

    # Test role
    - systemctl restart sshd

stages:
  - test
